import {StyleSheet} from 'react-native';

import colors from '../../helper/colors';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.mainColor,
  },
  arrowBack: {
    position: 'absolute',
    width: 25,
    height: 20,
    top: 41,
    left: 37,
  },
  logo: {
    position: 'absolute',
    top: 85,
    left: 165,
    width: 84,
    height: 64,
  },
  logo2: {
    width: 220,
    height: 167,
    top: 89,
    left: 97,
  },
  inputicon: {
    right: '20%',
    top: '5%',
    bottom: '50%',
  },
  inputtxt: {
    left: 6,
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20.11,
  },
  input2: {
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 320,
    height: 47,
    top: 293,
    left: 47,
    right: 2,
    borderStyle: 'solid',
    borderWidth: 2,
    borderBottomColor: colors.greyColor,
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20.11,
  },
  input3: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    width: 320,
    height: 47,
    top: 402,
    left: 47,
    right: 2,
    borderStyle: 'solid',
    borderWidth: 1,
    borderBottomColor: colors.greyColor,
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20.11,
  },
  btn2: {
    position: 'absolute',
    width: 77,
    height: 30,
    left: 168,
    top: 481,
    backgroundColor: colors.greyColor,
    borderRadius: 7,
  },
  btn2text: {
    paddingLeft: 18,
    paddingTop: 5,
    color: colors.whiteColor,
    fontFamily: 'Source Sans Pro',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
  },
  fpass: {
    position: 'absolute',
    width: 165,
    height: 25,
    left: 131,
    right: 131,
    top: 547,
  },
  fpasstext: {
    fontFamily: 'Source Sans Pro',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 25.14,
    color: colors.blueColor,
  },
  txt2: {
    color: colors.greyColor,
    fontFamily: 'Source Sans Pro',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
  },
  txt2Container: {
    position: 'absolute',
    width: 130,
    height: 31,
    left: 155,
    top: 684,
  },
  fingerPrintContainer: {
    position: 'absolute',
    width: 73.49,
    height: 68.33,
    top: 590.83,
    left: 185.24,
    right: '12.53%',
  },
  SignuptxtContainer: {
    flexDirection: 'row',
    position: 'absolute',
    width: 163,
    height: 20,
    left: 124,
    top: 750,
  },
  Signuptxt: {
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20.11,
    color: colors.greyColor,
  },
  lastContainer: {
    position: 'absolute',
    width: 370,
    height: 36,
    top: 816,
    left: 18,
  },
  lastContainerTxt: {
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    color: colors.greyColor,
  },
});

export default styles;
