import {StyleSheet} from 'react-native';
import colors from '../../helper/colors';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.mainColor,
  },
  logo: {
    position: 'absolute',
    top: 85,
    left: 165,
    width: 84,
    height: 64,
  },
  logo2: {
    width: 220,
    height: 167,
    top: 89,
    left: 97,
  },
  btnsignUp: {
    position: 'absolute',
    width: 77,
    height: 25,
    left: 77,
    top: 235,
  },
  signUptext: {
    fontFamily: 'Source Sans Pro',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 25,
    color: colors.blueColor,
  },
  btnLogin: {
    position: 'absolute',
    width: 70,
    height: 25,
    left: 274,
    top: 232,
  },
  Logintext: {
    fontFamily: 'Source Sans Pro',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 25,
    color: colors.greyColor,
  },
  icon1: {
    right: '20%',
    top: '5%',
    bottom: '50%',
  },
  input1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    width: 320,
    height: 47,
    top: 274,
    left: 48,
    right: 2,
    borderStyle: 'solid',
    borderWidth: 1,
    borderBottomColor: colors.greyColor,
  },
  input1txt: {
    left: 6,
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20.11,
  },
  input2: {
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 320,
    height: 47,
    top: 353,
    left: 47,
    right: 2,
    borderStyle: 'solid',
    borderWidth: 2,
    borderBottomColor: colors.greyColor,
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20.11,
  },
  input3: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    width: 320,
    height: 47,
    top: 432,
    left: 47,
    right: 2,
    borderStyle: 'solid',
    borderWidth: 1,
    borderBottomColor: colors.greyColor,
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20.11,
  },
  btn2: {
    position: 'absolute',
    width: 77,
    height: 30,
    left: 168,
    top: 515,
    backgroundColor: colors.greyColor,
    borderRadius: 7,
  },
  btn2text: {
    paddingLeft: 12,
    paddingTop: 5,
    color: '#FFFFFF',
    fontFamily: 'Source Sans Pro',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
  },
  txt2: {
    color: '#5E5E5E',
    fontFamily: 'Source Sans Pro',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
  },
  txt2Container: {
    position: 'absolute',
    width: 121,
    height: 20,
    left: 147,
    top: 665,
  },
  fingerPrintContainer: {
    position: 'absolute',
    width: 73.49,
    height: 68.33,
    top: 590.83,
    left: 180.24,
    right: '12.53%',
  },
  LogintxtContainer: {
    flexDirection: 'row',
    position: 'absolute',
    width: 163,
    height: 20,
    left: 124,
    top: 750,
  },
  Logintxt: {
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20.11,
    color: colors.greyColor,
  },
  lastContainer: {
    position: 'absolute',
    width: 370,
    height: 66,
    top: 816,
    left: 18,
  },
  lastContainerTxt: {
    fontFamily: 'Source Sans Pro',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    color: colors.greyColor,
  },
});

export default styles;
